site_name: Qyet
repo_url: https://github.com/vbuxbaum/qyet
repo_name: vbuxbaum/qyet
edit_uri: tree/main/docs/

theme:
  name: material
  palette:
    primary: green
    accent: amber

markdown_extensions:
  - attr_list

extra_css:
  - stylesheet/extra.css