site_name: Qyet
repo_url: https://github.com/vbuxbaum/qyet
repo_name: vbuxbaum/qyet
edit_uri: tree/main/docs/

theme:
  name: material
  favicon: assets/logo.png
  palette:
    primary: green
    accent: amber

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheet/extra.css